cmf_routing_auto:
    mappings:
        Symfony\Cmf\Bundle\BlogBundle\Document\Blog:
            content_path:
                routing_path:
                    provider: [specified, { path: cms/routes }]
                    exists_action: use
                    not_exists_action: throw_exception
                namespace:
                    provider: [specified, { path: blog }]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method,{ method: getName }]
                exists_action: auto_increment
                not_exists_action: create
        Symfony\Cmf\Bundle\BlogBundle\Document\Post:
            content_path:
                routing_path:
                    provider: [content_object, { method: getBlog }]
                    exists_action: use
                    not_exists_action: throw_exception
                date:
                    provider: [content_datetime, {method: getDate}]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method, {method: getTitle}]
                exists_action: auto_increment
                not_exists_action: create
